name = "Arneman"
license = "MIT"
licenselink = ""
description = "A minimalistic and responsive theme for bloggers."
homepage = "https://arneman.me"
tags = ["blog", "beautiful", "disqus", "rss", "syntax highlighting", "tags"]
features = ["blog", "beautiful", "disqus", "rss", "syntax highlighting", "tags"]
min_version = 0.20

[author]
  name = "bearlikelion"
  homepage = "https://github.com/bearlikelion"

[[original]]
  name = "Cactus Plus"
  homepage = "https://github.com/nodejh/hugo-theme-cactus-plus"
  repo = "https://github.com/nodejh/hugo-theme-cactus-plus"
